# Generated by Django 6.0.5 on 2026-05-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_data', models.JSONField()),
                ('docx_file', models.FileField(blank=True, upload_to='generated/docx/')),
                ('pdf_file', models.FileField(blank=True, upload_to='generated/pdf/')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('completed', 'Tayyor')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yaratilgan hujjat',
                'verbose_name_plural': 'Yaratilgan hujjatlar',
            },
        ),
    ]
